---
title: "Single_Cell_Seurat"
output: html_document
date: '2022-06-07'
---


#P0

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r}
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "~/Documents/Mythreye_Lab/Single_cell_mehri/run_count_P0")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, min.cells = 1, min.features = 200)
pbmc

```
```{r}
#add meta separately 
x1 <- rep("P0", each= 16961)
pbmc <- AddMetaData(object= pbmc, metadata = x1, col.name= "time")
```

```{r}
# Visualize QC metrics as a violin plot
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by= )
```

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2
```

```{r}
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500)

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
pbmc <- FindVariableFeatures(pbmc, selection.method = "mvp", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1
```

```{r}
plot2
```

```{r}
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
```

```{r}
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
```

```{r}
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)
```

```{r}
VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(pbmc, reduction = "pca", group.by= )
```

```{r}
DimHeatmap(pbmc, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
pbmc <- JackStraw(pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(pbmc, dims = 1:20)
```

```{r}
JackStrawPlot(pbmc, dims = 1:15)
```

```{r}
ElbowPlot(pbmc)
```

```{r}
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
```

```{r}
pbmc <- RunUMAP(pbmc, dims = 1:3)
DimPlot(pbmc, reduction = "umap")
```

```{r}
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)

write.csv(pbmc.markers, "~/Desktop/P0_genes_subgroups.csv")
```

#P7

```{r}
# Load the PBMC dataset
pbmc.data_1 <- Read10X(data.dir = "~/Documents/Mythreye_Lab/Single_cell_mehri/run_count_P7")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc_1 <- CreateSeuratObject(counts = pbmc.data_1, min.cells = 1, min.features = 200)
pbmc_1
```

```{r}
#add meta separately 
x2 <- rep("P7", each= 14029)
pbmc_1 <- AddMetaData(object= pbmc_1, metadata = x2, col.name= "time")
```

```{r}
# Visualize QC metrics as a violin plot
VlnPlot(pbmc_1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by= )
```

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot2 <- FeatureScatter(pbmc_1, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2
```

```{r}
pbmc_1 <- subset(pbmc_1, subset = nFeature_RNA > 200 & nFeature_RNA < 2500)

pbmc_1 <- NormalizeData(pbmc_1, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
pbmc_1 <- FindVariableFeatures(pbmc_1, selection.method = "mvp", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc_1), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc_1)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1
```

```{r}
plot2
```

```{r}
all.genes <- rownames(pbmc_1)
pbmc_1 <- ScaleData(pbmc_1, features = all.genes)
```

```{r}
pbmc_1 <- RunPCA(pbmc_1, features = VariableFeatures(object = pbmc_1))
```

```{r}
print(pbmc_1[["pca"]], dims = 1:5, nfeatures = 5)
```

```{r}
VizDimLoadings(pbmc_1, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(pbmc_1, reduction = "pca", group.by= )
```

```{r}
DimHeatmap(pbmc_1, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
pbmc_1 <- JackStraw(pbmc_1, num.replicate = 100)
pbmc_1 <- ScoreJackStraw(pbmc_1, dims = 1:20)
```

```{r}
JackStrawPlot(pbmc_1, dims = 1:15)
```

```{r}
ElbowPlot(pbmc_1)
```

```{r}
pbmc_1 <- FindNeighbors(pbmc_1, dims = 1:10)
pbmc_1 <- FindClusters(pbmc_1, resolution = 0.5)
```

```{r}
pbmc_1 <- RunUMAP(pbmc_1, dims = 1:3)
DimPlot(pbmc_1, reduction = "umap")
```

```{r}
pbmc.markers <- FindAllMarkers(pbmc_1, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)
write.csv(pbmc.markers, "~/Desktop/P7_genes_subgroups.csv")
```


#Merging 
```{r}
pbmc.combined <- merge(pbmc, y = pbmc_1, add.cell.ids = c("P0", "P7"), project = "P0_P7")
pbmc.combined
```
```{r}
# Visualize QC metrics as a violin plot
VlnPlot(pbmc.combined, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by= )
```

```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.

plot2 <- FeatureScatter(pbmc.combined, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2
```
```{r}
pbmc.combined <- subset(pbmc.combined , subset = nFeature_RNA > 200 & nFeature_RNA < 2500)

pbmc.combined  <- NormalizeData(pbmc.combined , normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
pbmc.combined <- FindVariableFeatures(pbmc.combined, selection.method = "mvp", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc.combined), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc.combined)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1
```

```{r}
plot2
```

```{r}
all.genes <- rownames(pbmc.combined)
pbmc.combined <- ScaleData(pbmc.combined, features = all.genes)
```

```{r}
pbmc.combined <- RunPCA(pbmc.combined, features = VariableFeatures(object = pbmc.combined))
```

```{r}
print(pbmc.combined[["pca"]], dims = 1:5, nfeatures = 5)
```

```{r}
VizDimLoadings(pbmc.combined, dims = 1:2, reduction = "pca")
```

```{r}
DimPlot(pbmc.combined, reduction = "pca", group.by= )
```

```{r}
DimHeatmap(pbmc.combined, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
pbmc.combined <- JackStraw(pbmc.combined, num.replicate = 100)
pbmc.combined <- ScoreJackStraw(pbmc.combined, dims = 1:20)
```

```{r}
JackStrawPlot(pbmc.combined, dims = 1:15)
```

```{r}
ElbowPlot(pbmc.combined)
```

```{r}
pbmc.combined <- FindNeighbors(pbmc.combined, dims = 1:10)
pbmc.combined <- FindClusters(pbmc.combined, resolution = 0.5)
```

```{r}
pbmc.combined <- RunUMAP(pbmc.combined, dims = 1:3)
```


```{r}
DimPlot(pbmc.combined, reduction = "umap")
```


```{r}
DimPlot(object = pbmc.combined, reduction = "umap", group.by = "time")
```


```{r}
pbmc.markers <- FindAllMarkers(pbmc.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>%
    group_by(cluster) %>%
    slice_max(n = 2, order_by = avg_log2FC)
write.csv(pbmc.markers, "~/Desktop/P0_P7_genes_subgroups.csv")
```
```{r}
pbmc$dataset  <- 'P0'
pbmc_1$dataset <- 'P7'
combined <- merge(x = pbmc, y = pbmc_1, add.cell.ids = c("P0", "P7"))

DimPlot(pbmc.combined, group.by = 'dataset', pt.size = 0.1)
```